version: 0.0
os: linux
files:
  - source: ./
    destination: /tmp/myapp
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: ec2-user
  AfterInstall:
    - location: scripts/after_install.sh
      runas: ec2-user
  ApplicationStart:
    - location: scripts/entrypoint.sh
      runas: ec2-user
